input_data:
  amsterdam100m_grid:  data/input/TooBigData/Amsterdam/grid100Amsterdam.shp
  amsterdam_predicting_no2_allmodels: data/input/TooBigData/Amsterdam/Predicting NO2-AllModelsAmsterdam100_xy.csv


out_location:
  data/output/06 predicting/