input_data:
  Amsterdam_NO2PredictionPerModel: data\output\06 predicting\Amsterdam_NO2PredictionPerModel.gpkg
  Amsterdam_NO2PredictionPerModel_ga: data\output\06 predicting\Amsterdam_NO2PredictionPerModel_ga.gpkg
  Bayreuth_NO2PredictionPerModel: data\output\06 predicting\Bayreuth_NO2PredictionPerModel.gpkg
  Bayreuth_NO2PredictionPerModel_ZI: data\output\06 predicting\Bayreuth_NO2PredictionPerModel_ZI.gpkg
  Hamburg_NO2PredictionPerModel: data\output\06 predicting\Hamburg_NO2PredictionPerModel.gpkg
  Utrecht_NO2PredictionPerModel: data\output\06 predicting\Utrecht_NO2PredictionPerModel.gpkg

  # modeling_dataset_global: \data\input\GlobalModelData\ModellingDataset-Global.shp
  modeling_dataset_global: \data\input\GlobalModelData\ModellingDataset-Global.csv
  modeling_dataset_local: data\input\LocalModelData\ModellingDataset-Local.csv

  all_models: data\output\07 evaluating\all_models_output\all_models.gpkg

  predictedNO2_Linear: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_Linear.gpkg
  predictedNO2_Linear_SeparatingSpatialGroups: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_Linear_SeparatingSpatialGroups.gpkg
  predictedNO2_MEM: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_MEM.gpkg
  predictedNO2_OK: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_OK.gpkg
  predictedNO2_UK_formula: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_UK_formula.gpkg
  predictedNO2_UK_SeparatingSpatialGroups: data\input\TooBigData\Amsterdam\LocalModels\predictedNO2_UK_SeparatingSpatialGroups.gpkg

  no2tif: data\input\no2_Amsterdam\no2.tif

  amsterdam_shape: data\input\SpatialPlaces\Amsterdam.shp
  bayreuth_shape: data\input\SpatialPlaces\Bayreuth.shp
  hamburg_shape: data\input\SpatialPlaces\Hamburg.shp
  utrecht_shape: data\input\SpatialPlaces\Utrecht.shp

out_location:
  data\output\07 evaluating\\
