global:
  no2: data/input/GlobalModelData/InitialGlobalDataset.csv
  precipitation_tifs: data/input/Precipitation/TIFS/
  building_processed: data/input/BuildingDensity/processed/BldDen_ms_StudyArea_Global.shp
  ndvi_processed: data/input/NDVI/processed/ms_NDVI_global.shp
  traffic_processed: data/input/Traffic/processed/traffic_NO2_Global.shp

local:

out_location:
  data/output/02 composing initial dataset/