input_data:
  amsterdam100m_grid:  data/input/TooBigData/Amsterdam/grid100Amsterdam.shp
  bayreuth100m_grid:  data/input/TooBigData/Bayreuth/grid100Bayreuth.gpkg
  hamburg100m_grid:  data/input/TooBigData/Hamburg/grid100Hamburg.gpkg
  utrecht100m_grid:  data/input/TooBigData/Utrecht/grid100Utrecht.gpkg
  ndvi_map: data/input/NDVI/
  traffic_volume_study_area: data/input/Traffic/TrafficVolume_StudyArea.shp
  modeling_dataset_local_processed: data/input/LocalModelData/ModellingDataset-Local-processed.csv
  polygonbuilding_studyArea: data/input/BuildingDensity/polygonbuilding_studyArea.shp
  polygonbuilding_DNL: data/input/TooBigData/polygonbuildings_DNL.shp
  grid_bldden_amsterdam: data/output/04 composing dataset/grid_bldden_100m_amsterdam.shp
  grid_bldden_bayreuth: data/output/04 composing dataset/grid_bldden_100m_bayreuth.shp
  grid_bldden_hamburg: data/output/04 composing dataset/grid_bldden_100m_hamburg.shp
  grid_bldden_utrecht: data/output/04 composing dataset/grid_bldden_100m_utrecht.shp

  globaldataset: data/input/GlobalModelData/PredictingDataset.csv
  localdataset: data/input/LocalModelData/PredictingDataset.csv

  
tifs:
  tifs5_amsterdam: data/input/TooBigData/Amsterdam/5TIFS/
  tifs8_bayreuth: data/input/TooBigData/Bayreuth/TIFFS/8/
  tifs1_hamburg: data/input/TooBigData/Hamburg/TIFFS/1/
  tifs7_utrecht: data/input/TooBigData/Utrecht/TIFFS/7/


out_location:
  data/output/04 composing dataset/

out_files:
  bayreuth_100mgrid: 'Cen100_GlobalPredictors-Bayreuth.gpkg'
  hamburg_100mgrid: 'Cen100_GlobalPredictors_Hamburg.gpkg'
  bayreuth_100mgrid_csv: 'grid100_GlobalPredictors-Bayreuth.csv'
  amsterdam_100mgrid_csv: 'grid100_GlobalPredictors-Amsterdam.csv'
  