global:
  base: dirname(current_dir)
  buildings: data\input\BuildingDensity\polygon_studyArea.shp
  no2: data\input\GlobalModelData\InitialGlobalDataset.csv
  ndvi_map: data\input\NDVI

out_location: data\output
